name: Build-Deploy-testnet
on:
  push:
    branches: [testnet]

env: 
  APP_NAME: bitorbit-sponsor
  REPO: ${{ secrets.REGISTRY_HOST }}/bitorbit
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker-build:
    name: Build and push
    runs-on: testnet-services
    steps:
      - uses: actions/checkout@v3
      - name: Build, tag, and push image 
        id: build
        run: |
          docker build -t $REPO/$APP_NAME:$IMAGE_TAG --no-cache .
          docker tag $REPO/$APP_NAME:$IMAGE_TAG $REPO/$APP_NAME:${{ github.ref_name }}
          docker push $REPO/$APP_NAME:$IMAGE_TAG
          docker push $REPO/$APP_NAME:${{ github.ref_name }}
  deploy:
    name: Deploy via Helmfile
    runs-on: testnet-services
    needs: docker-build
    steps:
      - name: Check out bitorbit-infra
        uses: actions/checkout@v3
        with:
          repository: BitorbitLabs/bitorbit-infra
          ref: master
          ssh-key: ${{ secrets.SSH_KEY_INFRA }}
      - name: Deploy via helmfile
        id: deploy
        env:
          SOPS_AGE_KEY: ${{ secrets.INFRA_AGE }}
        run: >
          cd deploy &&
          helmfile -e ${HELM_ENV} -l namespace=${NAMESPACE},name=${{ env.APP_NAME }}
          apply --set image.tag=$IMAGE_TAG,image.repository=$REPO/$APP_NAME
          --skip-deps --suppress-diff
